### ISSUE TITLE
Jumping is not working.

### ISSUE THREAD

**Issue by Acertain42** [FriendSea/PlatformerRails#1]
Jumping does not work.
If I change the code to GetButton instead of GetButtonDown it will work. This is undesirable.

**Comment by chocola-mint** [comment]
> Jumping does not work. If I change the code to GetButton instead of GetButtonDown it will work. This is undesirable.

This is because "GetButtonDown" is updated per-Update, not per-FixedUpdate, so it's possible to miss the frame where GetButtonDown returns true.

The check needs to be moved into Update instead. (The code that needs to be fixed is [here](https://github.com/FriendSea/PlatformerRails/blob/master/SampleProject/Assets/PlatformerRails/Demo/PlayerMove.cs#L50).)

I can submit a pull request later, or perhaps the author could take over from here instead. @FriendSea
